# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/User/Downloads/working-1July2021/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_example_design.xdc

# XDC: C:/Users/User/Downloads/working-1July2021/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_user_phytiming.xdc

# XDC: new/file_debug.xdc

# Block Designs: bd/udp_block/udp_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_block || ORIG_REF_NAME==udp_block}]

# IP: bd/udp_block/ip/udp_block_app_layer_0_0/udp_block_app_layer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_block_app_layer_0_0 || ORIG_REF_NAME==udp_block_app_layer_0_0}]

# IP: bd/udp_block/ip/udp_block_app_recv_0_0/udp_block_app_recv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_block_app_recv_0_0 || ORIG_REF_NAME==udp_block_app_recv_0_0}]

# IP: bd/udp_block/ip/udp_block_axi_buf_send_0_0/udp_block_axi_buf_send_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_block_axi_buf_send_0_0 || ORIG_REF_NAME==udp_block_axi_buf_send_0_0}]

# IP: bd/udp_block/ip/udp_block_toplevel_0_0/udp_block_toplevel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_block_toplevel_0_0 || ORIG_REF_NAME==udp_block_toplevel_0_0}]

# IP: bd/udp_block/ip/udp_block_axi_buf_recv_final_0_0/udp_block_axi_buf_recv_final_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_block_axi_buf_recv_final_0_0 || ORIG_REF_NAME==udp_block_axi_buf_recv_final_0_0}]

# XDC: bd/udp_block/udp_block_ooc.xdc
