set_property SRC_FILE_INFO {cfile:C:/Users/User/Downloads/working-1July2021/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_example_design.xdc rfile:../../../imports/tri_mode_ethernet_mac_0_example_design.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/User/Downloads/working-1July2021/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/constrs_1/new/file_debug.xdc rfile:../../../tri_mode_ethernet_mac_0_ex.srcs/constrs_1/new/file_debug.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports clk_in_p]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports clk_in_n]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports glbl_rst]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports frame_error]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports frame_errorn]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports activity_flash]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports activity_flashn]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports update_speed]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6 [get_ports config_board]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB12 [get_ports pause_req_s]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports reset_error]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y28 [get_ports {mac_speed[0]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA28 [get_ports {mac_speed[1]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W29 [get_ports gen_tx_data]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y29 [get_ports chk_tx_data]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports phy_resetn]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ24 [get_ports serial_response]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK25 [get_ports tx_statistics_s]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25 [get_ports rx_statistics_s]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R23 [get_ports mdc]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports mdio]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U28 [get_ports {rgmii_rxd[3]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T25 [get_ports {rgmii_rxd[2]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U25 [get_ports {rgmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U30 [get_ports {rgmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L28 [get_ports {rgmii_txd[3]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M29 [get_ports {rgmii_txd[2]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N25 [get_ports {rgmii_txd[1]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N27 [get_ports {rgmii_txd[0]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M27 [get_ports rgmii_tx_ctl]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K30 [get_ports rgmii_txc]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R28 [get_ports rgmii_rx_ctl]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U27 [get_ports rgmii_rxc]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC17 [get_ports gtx_clk_bufg_out]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_in_p 0.050
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_ports update_speed] 4.000
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells tx_stats_toggle_reg] -to [get_cells tx_stats_sync/data_sync_reg0] 6.000
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells rx_stats_toggle_reg] -to [get_cells rx_stats_sync/data_sync_reg0] 6.000
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/rd_addr_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/wr_store_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *fifo_i/resync_wr_store_frame_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/update_addr_tog_reg}] -to [get_cells -hier -filter {name =~ *rx_fifo_i/sync_rd_addr_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_addr_txfer_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frame_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frame_in_fifo/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frames_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frames_in_fifo/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/frame_in_fifo_valid_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_fif_valid_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_txfer_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_txfer_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_tran_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_tran_frame_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/app_layer_0/inst/count[3]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/app_layer_0/inst/count[4]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/app_layer_0/inst/count[0]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/app_layer_0/inst/count[1]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/app_layer_0/inst/count[2]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[30]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[27]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[21]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[18]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[24]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[15]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[12]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[7]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[5]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[2]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[3]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[9]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[10]}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[0]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[1]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[4]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[6]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[8]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[14]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[16]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[19]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[17]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[13]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[26]}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[25]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[22]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[23]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[20]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[31]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[28]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[29]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[11]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[10]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[13]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[9]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[3]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[1]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[4]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[2]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[0]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[7]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[6]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[5]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[14]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[15]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[12]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[8]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[11]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][8]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][12]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][24]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][18]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][21]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][15]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][30]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][27]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][6]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][3]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][0]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][9]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][1]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][2]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][4]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][5]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][7]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][13]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][14]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][11]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][17]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][16]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][22]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][19]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][20]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][25]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][26]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][23]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][29]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][28]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][31]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][10]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list example_clocks/clock_generator/CLK_OUT1]]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {udp_module/udp_block_i/app_layer_0/inst/count[0]} {udp_module/udp_block_i/app_layer_0/inst/count[1]} {udp_module/udp_block_i/app_layer_0/inst/count[2]} {udp_module/udp_block_i/app_layer_0/inst/count[3]} {udp_module/udp_block_i/app_layer_0/inst/count[4]}]]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_support_clocking_i/clk_out1]]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[0]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[1]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[2]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[3]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[4]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[5]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[6]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[7]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[8]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[9]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[10]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[11]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[12]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[13]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[14]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app_length[15]}]]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][0]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][1]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][2]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][3]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][4]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][5]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][6]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][7]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][8]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][9]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][10]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][11]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][12]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][13]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][14]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][15]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][16]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][17]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][18]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][19]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][20]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][21]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][22]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][23]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][24]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][25]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][26]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][27]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][28]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][29]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][30]} {udp_module/udp_block_i/toplevel_0/inst/IP_send_module/data_out_reg[31][31]}]]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[0]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[1]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[2]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[3]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[4]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[5]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[6]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[7]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[8]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[9]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[10]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[11]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[12]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[13]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[14]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[15]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[16]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[17]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[18]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[19]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[20]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[21]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[22]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[23]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[24]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[25]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[26]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[27]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[28]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[29]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[30]} {udp_module/udp_block_i/toplevel_0/inst/udp_send_module/data_out_from_app[31]}]]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets tx_mac_aclk]
